name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          cat <<EOF > .env
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          EOF

      - name: Build Docker image
        run: docker build -t frontend:latest .

      - name: Save Docker image to file
        run: docker save frontend:latest -o frontend.tar

      - name: Prepare deploy files
        run: |
          mkdir frontend
          mv frontend.tar docker-compose.yml frontend/

      - name: Copy Docker image and .env to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "frontend/*"
          target: "~/"

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/frontend

            docker compose down || true
            docker rmi frontend:latest || true
            
            docker load -i frontend.tar
            rm frontend.tar
            
            docker compose up -d
